// USERS
export const RESET_USERS = 'RESET_USERS';
export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';

// FILTERS
export const SET_FILTERS = 'SET_FILTERS';
export const RESET_FILTERS = 'RESET_FILTERS';

// TODOS
export const FETCH_TODOS = 'FETCH_TODOS';
export const FETCH_TODOS_START = 'FETCH_TODOS_START';
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS';
export const FETCH_TODOS_FAIL = 'FETCH_TODOS_FAIL';

// FETCHERS
export const ADD_FETCHING = 'ADD_FETCHING';
export const REMOVE_FETCHING = 'REMOVE_FETCHING';
export const ADD_FETCHED = 'ADD_FETCHED';
export const REMOVE_FETCHED = 'REMOVE_FETCHED';
